### ISSUE TITLE
Unable to resolve symbol: mp4-file-path->markdown-html in this context

### ISSUE THREAD

**Issue by wangtengda0310** [bbss/cljsc2#4]
![default](https://user-images.githubusercontent.com/17254793/38907452-64c55ae2-42ee-11e8-8df7-068846ae5a4f.png)

**Comment by bbss** [comment]
Okay, I've been working on a different branch lately. Have a lot of nice UI features coming up.

I've [pushed](https://github.com/bbss/cljsc2/commit/a8434caa8eac540fd31dae514d092ad37aa51f13)  a fix to this import issue you were having.
please `git pull` and try again.
